### ISSUE TITLE
s3 support assumption

### ISSUE THREAD

**Issue by zhangzqs** [helyim/helyim#76]
If it support s3 api, it must store some s3 object matedata like bucket, key, fid, ...
Does it require the use of a database? We need to write a lot of s3 logic?
Is there a solution where you can just use this project as the data storage backend and not care about the implementation of S3 metadata and logic?

**Comment by iamazy** [comment]
Hi, @zhangzqs 

S3 will be implemented through the Filer service and Filer accessing other databases (such as Redis) to store S3 metadata. more details could be found in [Filer](https://github.com/seaweedfs/seaweedfs/wiki/Directories-and-Files).

helyim will utilize [s3s](https://github.com/Nugine/s3s) to implement S3 service

**Comment by zhangzqs** [comment]
> Hi, @zhangzqs
> 
> S3 will be implemented through the Filer service and Filer accessing other databases (such as Redis) to store S3 metadata. more details could be found in [Filer](https://github.com/seaweedfs/seaweedfs/wiki/Directories-and-Files).
> 
> helyim will utilize [s3s](https://github.com/Nugine/s3s) to implement S3 service

ok, thanks for your reply
